Repository Rukkaitto/mobichan, pull requests merged in 2021-11, with the labels that each got.

#27 Webm player back button crashes
  android/app/build.gradle
  lib/pages/webm_viewer_page.dart
  lib/widgets/video_player_widget/video_player_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: fix

#29 Converted board list page to stacked architecture
  ios/Podfile.lock
  lib/app.dart
  lib/classes/viewmodels/filtered_future_view_model.dart
  lib/main.dart
  lib/pages/boards/board_tile/board_tile_view.dart
  lib/pages/boards/board_tile/board_tile_viewmodel.dart
  lib/pages/boards/boards_view.dart
  lib/pages/boards/boards_viewmodel.dart
  lib/pages/boards_list_page.dart
  lib/routes/routes.dart
  lib/routes/routes.locator.dart
  lib/routes/routes.router.dart
  lib/widgets/drawer_widget/drawer_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: refactoring

#28 Webms in gallery mode
  lib/pages/image_carousel_page.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#31 Webms playing in the background when swiped
  lib/pages/image_carousel_page.dart
  lib/pages/webm_viewer_page.dart
  lib/widgets/post_widget/components/post_image.dart
  lib/widgets/video_player_widget/video_player_widget.dart
Labels: fix

#34 Added dependency injection with the get_it package
  lib/app.dart
  lib/dependency_injector.dart
  lib/main.dart
  lib/pages/boards/cubit/boards_cubit/boards_cubit.dart
  lib/pages/boards/cubit/favorite_cubit/favorite_cubit.dart
  lib/pages/boards/view/board_list_tile.dart
  lib/pages/boards/view/boards_view.dart
  lib/widgets/drawer/cubit/favorites_cubit/favorites_cubit.dart
  lib/widgets/drawer/cubit/package_info_cubit/package_info_cubit.dart
  lib/widgets/drawer/view/drawer_view.dart
  packages/mobichan_data/lib/src/features/board/datasources/local_datasource.dart
  packages/mobichan_data/lib/src/features/board/datasources/remote_datasource.dart
  packages/mobichan_data/lib/src/features/board/repositories/repository_impl.dart
  packages/mobichan_data/lib/src/features/captcha/datasources/remote_datasource.dart
  packages/mobichan_data/lib/src/features/post/datasources/local_datasource.dart
  packages/mobichan_data/lib/src/features/post/datasources/remote_datasource.dart
  packages/mobichan_data/lib/src/features/release/datasources/remote_datasource.dart
  packages/mobichan_data/lib/src/features/sort/datasources/local_datasource.dart
Labels: refactoring

#35 Changed how the error message is handled for posting
  assets/script.js
  assets/translations/en-US.json
  assets/translations/fr-FR.json
  files/captcha.html
  lib/localization.dart
  lib/pages/board_page.dart
  lib/pages/boards/cubit/boards_cubit/boards_cubit.dart
  lib/pages/thread_page.dart
  lib/widgets/form_widget/form_widget.dart
  packages/mobichan_data/lib/src/core/exceptions/chan_exception.dart
  packages/mobichan_data/lib/src/core/exceptions/exceptions.dart
  packages/mobichan_data/lib/src/features/post/datasources/remote_datasource.dart
  packages/mobichan_data/lib/src/features/post/repositories/repository_impl.dart
  packages/mobichan_data/pubspec.lock
  packages/mobichan_data/pubspec.yaml
  packages/mobichan_domain/lib/src/features/post/repositories/repository.dart
  pubspec.yaml
Labels: refactoring

#36 Fixed broken webms
  lib/pages/image_carousel_page.dart
  lib/widgets/video_player_widget/video_player_widget.dart
Labels: bug

#38 Swapped http.Client with Dio in remote datasources
  lib/dependency_injector.dart
  lib/widgets/form_widget/form_widget.dart
  packages/mobichan_data/lib/src/features/board/datasources/remote_datasource.dart
  packages/mobichan_data/lib/src/features/captcha/datasources/remote_datasource.dart
  packages/mobichan_data/lib/src/features/post/datasources/remote_datasource.dart
  packages/mobichan_data/lib/src/features/release/datasources/remote_datasource.dart
Labels: refactoring

#45 Splash screen
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-hdpi/background.9.png
  android/app/src/main/res/drawable-hdpi/title.9.png
  android/app/src/main/res/drawable-mdpi/background.9.png
  android/app/src/main/res/drawable-mdpi/title.9.png
  android/app/src/main/res/drawable-v21/launch_background.xml
  android/app/src/main/res/drawable-xhdpi/background.9.png
  android/app/src/main/res/drawable-xhdpi/title.9.png
  android/app/src/main/res/drawable-xxhdpi/background.9.png
  android/app/src/main/res/drawable-xxhdpi/title.9.png
  android/app/src/main/res/drawable-xxxhdpi/background.9.png
  android/app/src/main/res/drawable-xxxhdpi/title.9.png
  android/app/src/main/res/drawable/launch_background.xml
  android/app/src/main/res/values/colors.xml
Labels: feature
